#include "bootloader.h"
#include "RCUtils.h"
#include "logging.h"

#include <project.h>

#include "MotorBootloaderDefs.h"
#include "bootloader_spi.h"

#include "cytypes.h"
#include "cydevice.h"      /* CYDEV_SRAM_BASE / CYDEV_SRAM_SIZE */
#include "core_cm3.h"       /* NVIC, SCB */
#include "cmsis_gcc.h"      /* __set_MSP, __disable_irq */

#define APP_JUMP_TIMEOUT  5000  // 5 seconds

typedef void (*cy_app_entry_t)(void);

typedef struct
{
    uint32_t initial_sp;
    uint32_t reset_handler;
} cy_app_vectors_t;

typedef struct __attribute__((__packed__))
{
    uint32_t appCrc;
    uint32_t appStart;
    uint32_t appEnd;
} tMetaData_t;


CY_NOINIT static volatile uint32_t bootEntryFlag;
volatile uint8_t commsStarted = FALSE;

static volatile uint32 g_ms;

static uint8_t blParseCommand(const uint8_t* pData, uint16_t len);
static void blJumpToMainApp();
static void blDoUpgrade();
static cystatus BlWriteRow(uint32_t absoluteRow, const uint8_t rowData[CY_ROW_LENGTH]);
static cystatus BlCheckMetadata();
static cystatus BlWriteMetadata(uint32_t imageData, uint32_t imageCrc);
extern uint8_t blCommsPoll(uint8_t** rxBuffer, size_t* len);

/* DIAGNOSTIC: temporary stand-in for CyFlash_Start(), mirroring its exact
 * sequence (see CyFlash.c - not edited, it's regenerated by PSoC Creator)
 * but with prints, to find why CY_FLASH_EE_EE_AWAKE never sets. Swap the
 * call below back to the real CyFlash_Start() once this is root-caused. */
static void BlDiagnosticFlashStart(void)
{
    uint8 interruptState = CyEnterCriticalSection();

    // CY_FLASH_PM_ACT_CFG0_REG    |= CY_FLASH_PM_ACT_CFG0_EN_CLK_SPC;
    // CY_FLASH_PM_ALTACT_CFG0_REG |= CY_FLASH_PM_ALTACT_CFG0_EN_CLK_SPC;

    // CY_FLASH_SPC_FM_EE_WAKE_CNT_REG = CY_FLASH_SPC_FM_EE_WAKE_CNT_80MHZ;

    // CY_FLASH_PM_ACT_CFG12_REG    |= CY_FLASH_PM_ACT_CFG12_EN_FM;
    // CY_FLASH_PM_ALTACT_CFG12_REG |= CY_FLASH_PM_ALTACT_CFG12_EN_FM;

    // vLoggingPrintf(DEBUG_INFO, LOG_PSOC,
    //     "FlashStart: CFG0=0x%02X ALTCFG0=0x%02X CFG12=0x%02X ALTCFG12=0x%02X WAKE_CNT=0x%02X CR=0x%02X\r\n",
    //     CY_FLASH_PM_ACT_CFG0_REG, CY_FLASH_PM_ALTACT_CFG0_REG,
    //     CY_FLASH_PM_ACT_CFG12_REG, CY_FLASH_PM_ALTACT_CFG12_REG,
    //     CY_FLASH_SPC_FM_EE_WAKE_CNT_REG, CY_FLASH_SPC_FM_EE_CR_REG);

    uint32_t spins = 0u;
    // while (0u == (CY_FLASH_SPC_FM_EE_CR_REG & CY_FLASH_EE_EE_AWAKE))
    // {
    //     /* Non-zero status denotes that the EEPROM/Flash is awake & powered. */
    //     spins++;
    //     if ((spins & 0xFFFFu) == 0u)
    //     {
    //         vLoggingPrintf(DEBUG_INFO, LOG_PSOC,
    //             "FlashStart: still waiting, CR=0x%02X (spins=%lu)\r\n",
    //             CY_FLASH_SPC_FM_EE_CR_REG, (unsigned long) spins);
    //     }
    // }

    vLoggingPrintf(DEBUG_INFO, LOG_PSOC, "FlashStart: EE_AWAKE set, CR=0x%02X\r\n", CY_FLASH_SPC_FM_EE_CR_REG);

    CyExitCriticalSection(interruptState);
}

void Bootloader_Start()
{
    // Check if we should jump to the image or jump to bootloader mode
    Bootloader_SPI_Start();

    // Verify main app metadata
    CyEnterCriticalSection();
    vLoggingPrintf(DEBUG_INFO, LOG_PSOC, "Starting flash\r\n");

    (void) CySetTemp();
    CyFlash_Start();
    if (bootEntryFlag == BOOTLOADER_ENTRY_MAGIC)
    {
        vLoggingPrintf(DEBUG_INFO, LOG_PSOC, "Entering updating stage\r\n");
        blDoUpgrade();
    }
    vLoggingPrintf(DEBUG_INFO, LOG_PSOC, "Jumping to main app\r\n");
    blJumpToMainApp();
}

inline void SetCommsStarted()
{
    commsStarted = TRUE;
}

static void blJumpToMainApp()
{
    const cy_app_vectors_t *appVectors = (const cy_app_vectors_t *)APPL_START_ADDR;

    /* UART_Debug_TX_STS_COMPLETE is a one-shot, read-to-clear event bit, not
     * a state bit - vLoggingPrintf()'s own internal FIFO polling already
     * reads this same TXSTATUS_REG and silently clears it as a side effect,
     * so waiting on TX_STS_COMPLETE hangs forever (the event already fired
     * and was already consumed before we ever get here). Poll
     * TX_STS_FIFO_EMPTY instead - it reflects live FIFO occupancy on every
     * read rather than a one-shot latch - and bound the wait so a bootloader
     * never hangs forever on an unexpected hardware status bit.
     *
     * This MUST run before __disable_irq() below: the bound relies on g_ms,
     * which only advances via the SysTick ISR, so timing out here after
     * interrupts are already disabled would never actually time out. */
    uint32_t txFlushDeadline = g_ms + 10u;
    while (((UART_Debug_TXSTATUS_REG & UART_Debug_TX_STS_FIFO_EMPTY) == 0u) && (g_ms < txFlushDeadline))
    {
        /* wait for the last byte to leave the FIFO, but don't hang forever */
    }

    // Stop peripherals and interrupts
    __disable_irq();

    SPIS_ClearFIFO();
    SPIS_ClearRxBuffer();
    SPIS_ClearTxBuffer();
    SPIS_Stop();
    PWM_Stop();
    UART_Debug_Stop();

    for (uint32_t i = 0u; i < (sizeof(NVIC->ICER) / sizeof(NVIC->ICER[0])); i++)
    {
        NVIC->ICER[i] = 0xFFFFFFFFu;   /* disable every external interrupt */
        NVIC->ICPR[i] = 0xFFFFFFFFu;   /* and clear anything left pending */
    }

    __set_MSP(appVectors->initial_sp);
    /* reset_handler already has the Thumb bit (bit 0) set - it's a plain
     * function pointer as written into RomVectors[] by the compiler. */
    ((cy_app_entry_t)appVectors->reset_handler)();

    for (;;) { /* unreachable */ }
}

static void blDoUpgrade()
{
    uint8_t* rxPointer = NULL;
    size_t len = 0;
    uint8_t ret = Bl_Ok;
    uint32_t timeBeg = xGetTimestamp();
    while ((xGetElapsed(timeBeg) < APP_JUMP_TIMEOUT) && (ret != Bl_Finished))
    {
        if (blCommsPoll(&rxPointer, &len))
        {
            CHECK(rxPointer != NULL);
            const tBlXfer* hdr = (const tBlXfer*)rxPointer;
            blParseCommand((const uint8_t*)(hdr + 1), sizeof(tBlXfer));
        }
    }

    if (ret != Bl_Finished)
    {
        vLoggingPrintf(DEBUG_INFO, LOG_PSOC, "Failed to update app image\r\n");
    }
    else
    {
        vLoggingPrintf(DEBUG_INFO, LOG_PSOC, "Update finalized\r\n");

        // Wait 5 seconds before jumping to the image
        timeBeg = xGetTimestamp();
        uint8_t countDown = APP_JUMP_TIMEOUT % 1000;
        while(xGetElapsed(timeBeg) < APP_JUMP_TIMEOUT)
        {
            if (xGetElapsed(timeBeg) % 1000)
            {
                vLoggingPrintf(DEBUG_INFO, LOG_PSOC, "Jumping to image in %d seconds\r", countDown --);
            }
        }
    }
}

static uint8_t blParseCommand(const uint8_t* pData, uint16_t len)
{
    CHECK(pData != NULL);
    const tBlXfer* hdr = (const tBlXfer*)pData;
    static uint8_t verifyStatus = FALSE;
    cystatus ret;
    uint32_t crc = 0;
    static uint8_t stateReply = Bl_Ok;
    switch (hdr->cmd)
    {
        case BootLoader_Ping:
            vLoggingPrintf(DEBUG_INFO, LOG_PSOC, "Received Ping message from update server\r\n");
            Bootloader_SPI_SetResponse(Bl_Ping);  // Reply with the ping state
            break;
        case BootLoader_WriteRow:
            crc = xCRC32((uint8_t*)(hdr + 1), CY_ROW_LENGTH);
            if (crc == hdr->crc32)
            {
                Bootloader_SPI_SetResponse(Bl_WriteInProgress);
                ret = BlWriteRow(hdr->row, (uint8_t*)(hdr + 1));
                if (ret == CYRET_SUCCESS)
                {
                    stateReply = Bl_Ok;
                }
            }
            else
            {
                vLoggingPrintf(DEBUG_ERROR, LOG_PSOC, "Invalid CRC32 detected\r\n");
                stateReply = Bl_Err;
            }
            verifyStatus = crc == hdr->crc32;
            break;
        case Bootloader_Verify_Write:  // Does noithing
            break;
        case Bootloader_Finalize:
            stateReply = Bl_Finished;
        default:
            break;
    }

    Bootloader_SPI_SetResponse(stateReply);  // Stage the reply byte
    return stateReply;
}

static cystatus BlWriteRow(uint32_t absoluteRow, const uint8_t rowData[CY_ROW_LENGTH])
{
    /* absoluteRow is a ROW NUMBER (0-1023), not a byte address - comparing
     * it against APPL_METADATA (a byte address, 0x8000) was always true
     * and never actually rejected anything. CY_FIRST_APP_ROW is the same
     * boundary already expressed in row units. This also keeps the
     * metadata row itself (row 128, [0x8000,0x8100)) out of reach of the
     * normal WriteRow path - it's written only by Bootloader_Finalize. */
    if (absoluteRow < CY_FIRST_APP_ROW)
    {
        return CYRET_BAD_PARAM;
    }

    uint16_t arrayId    = (uint8_t ) (absoluteRow / (CY_FLASH_SECTOR_SIZE / CY_ROW_LENGTH));
    uint16_t rowInArray = (uint16_t) (absoluteRow % (CY_FLASH_SECTOR_SIZE / CY_ROW_LENGTH));
    return CyWriteRowData(arrayId, rowInArray, rowData);
}

static cystatus BlWriteMetadata(uint32_t imageData, uint32_t imageCrc)
{
    return CYRET_SUCCESS;
}

static cystatus BlCheckMetadata()
{
    // Make sure the metadata is present. Verify the omage if we must
    // CHECK(CyRead)
}