# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\cayod\OneDrive\Documents\Repos\RC-Car-peripheral-controller\src\rc-car-peripheral-controller\rc-car-peripheral-controller.cydsn\rc-car-peripheral-controller.cyprj
# Date: Fri, 24 Jul 2026 04:11:59 GMT
#set_units -time ns
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 16.666666666666664 -waveform {0 8.33333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 16.666666666666664 -waveform {0 8.33333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {timer_clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 7 13} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {SPIS_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 31 61} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {timer_clock_2} -source [get_pins {ClockBlock/clk_sync}] -edges {1 61 121} [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {timer_clock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 61 121} [list [get_pins {ClockBlock/dclk_glb_3}]]
create_generated_clock -name {UART_Debug_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 65 131} [list [get_pins {ClockBlock/dclk_glb_4}]]
create_generated_clock -name {Clock_3} -source [get_pins {ClockBlock/clk_sync}] -edges {1 601 1201} [list [get_pins {ClockBlock/dclk_glb_5}]]
create_generated_clock -name {TIMER_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 60001 120001} [list [get_pins {ClockBlock/dclk_glb_6}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\cayod\OneDrive\Documents\Repos\RC-Car-peripheral-controller\src\rc-car-peripheral-controller\rc-car-peripheral-controller.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\cayod\OneDrive\Documents\Repos\RC-Car-peripheral-controller\src\rc-car-peripheral-controller\rc-car-peripheral-controller.cydsn\rc-car-peripheral-controller.cyprj
# Date: Fri, 24 Jul 2026 04:11:49 GMT
